config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true, length: { minimum: 10 }
  validates :rating, numericality: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
    @review = Review.new
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :phone_number, :address)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to @review.restaurant
    else
      render 'restaurants/show'
    end
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
 <head>
  <title>RailsYelpMvp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
 <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 </head>
 <body>
  <%= yield %>
 </body>
</html>

app/views/restaurants/index.html.erb
<h1>TOUS LES RESTAURANTS</h1>

<% @restaurants.each do |restaurant| %>
<div class="card">
  <div class="card-body">
    <%= link_to restaurant.name, restaurant_path(restaurant.id) %>
  </div>
</div>
<% end %>

<p><%= link_to "Add a restaurant", new_restaurant_path %></p>

app/views/restaurants/new.html.erb
<div class="container justify-content-center">
  <h1>CREER UN NOUVEAU RESTAURANT</h1>
  <div class="col-12 col-lg-6 mt-5">
    <%= simple_form_for(@restaurant) do |f| %>
      <%= f.input :name, placeholder: :name %>
      <%= f.input :address, placeholder: :address %>
      <%= f.input :phone_number, placeholder: :phone_number %>
      <%= f.input :category, :collection => %w[chinese italian japanese french belgian] %>
      <%= f.button :submit, class: 'btn-primary btn-block' %>
    <% end %>
    <%= link_to "Go back", restaurants_path %>

  </div>
</div>

app/views/restaurants/show.html.erb
<div class="card">
  <div class="card-body">
    <h4 class="card-title"><%= @restaurant.name %></h5>
    <h5 class="card-subtitle mb-2 text-muted"><%= @restaurant.category %></h6>
    <p class="card-text"><%= @restaurant.address %></p>
    <p class="card-text"><%= @restaurant.phone_number %></p>

    <%= render 'reviews/form', review: @review %>

    <h5>Reviews</h5>
    <ul>
      <% @restaurant.reviews.each do |review| %>
        <li><%= review.content %> | <%= review.rating %> stars</li>
      <% end %>
    </ul>

  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, :collection => %w[0 1 2 3 4 5] %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<h1>ADD A REVIEW</h1>

<%= render 'form', review: @review %>